### ISSUE TITLE
License naming

### ISSUE THREAD

**Issue by ondrejfuhrer** [zachwick/homebrew-license#10]
Hey @zachwick ,

I was just playing around to use GitHub API in order to pull the license information about the Formula from the GitHub API (in the formula is hosted there).

I got a lot of "different" results, but I noticed that most of them (if I compare them with what we already have) is difference i.e. `GPL-2.0` vs `GPL-2.0-only`. So I started wondering, why do you include the `-only` or `-or-later` suffixes? I could ignore those, but I would like to know, why is is there? 

Maybe will be also good to mention that in the README if you;'re going to keep it there for a reason.

PS: I will later create a PR with that script (will add that as `brew` command so that you can use that as well if you want 🙂

**Comment by zachwick** [comment]
I think that adding the `-or-later` bit is very important if the project has specified that licensing scheme. If I haven't seen that kind of language on the project, I've been explicitly using the `-only` option just to be clear that there is no other license option available.

If your script pulls from the Github License API and receives a value of `GPL-2.0`, I'm fine using that instead of `GPL-2.0-only`. However, if a project has specifically mentioned "or later" or "only", then I'm of the opinion that we need to indicate those licensing choices.

**Comment by zachwick** [comment]
@ondrejfuhrer I’ve now added a `—fetch` option to the `license` command which attempts to pull a formula’s licensing information via the Github Licenses API. This is primarily to stop from having to run `brew info FORMULA` and then manually visiting the given homepage and digging for license information.

I will add some clarifying comments to the README about when to use `-only` and `-or-later` and then I think this issue can be closed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ondrejfuhrer** [comment]
@zachwick nice 👍 Thanks for the clarification and implementation!

**Comment by zachwick** [comment]
After doing some more digging, it appears that the Github License API is using deprecated SPDX identifiers. This explains why the Github License API returns things like `GPL-3.0` instead of `GPL-3.0-only` and `GPL-3.0+` instead of `GPL-3.0-or-later`.

I'm going to close this issue and open an issue on the GitHub API at https://github.community/t5/GitHub-API-Development-and/bd-p/api.
